title: Dr. XU, Hui 徐輝
logo: profile.png
description: I am a Pre-tenure Associate Professor in School of Computer Science, Fudan University. I obtained my Ph.D. degree from the Chinese University of Hong Kong in 2018, supervised by Prof. Michael Lyu.
theme: jekyll-theme-minimal
