title: Dr. XU, Hui 徐輝
logo: profile.png

description: I am a Pre-tenure Associate Professor in School of Computer Science, Fudan University. My research interests are within the fields of Software Security and Reliability, Program Analysis, and Usable Security and Privacy. I obtained my Ph.D. degree from the Chinese University of Hong Kong in 2018, supervised by Prof. Michael Lyu.

theme: jekyll-theme-minimal
