title: Dr. XU, Hui 徐輝
logo: profile.png

theme: jekyll-theme-minimal

description: Pre-tenure Associate Professor <br>School of Computer Science, Fudan University	<br>Email: xuh[AT]fudan.edu.cn	<br>Address:  Rm 328, Software Building,  Fudan University, <br> Pudong District, Shanghai, China <br> 青年副研究员 <br> 复旦大学 计算机学院 <br> 电邮：xuh[AT]fudan.edu.cn  <br> 地址：复旦大学张江校区 软件楼328室 <br> 上海市 浦东新区 张衡路825号
