title: Dr. XU, Hui 徐輝
logo: profile.png

description: -Pre-tenure Associate Professor School of Computer Science, Fudan University -Email: xuh[AT]fudan.edu.cn	-Address:  Rm 328, Software Building,  Fudan University, <br> Pudong District, Shanghai, China 
theme: jekyll-theme-minimal
